import type { ProbeEndpoint } from "../types/probe";

/**
 * Read-only endpoint inventory for the first H168 Probe. `evidence` controls
 * how the UI describes the endpoint; it is not a promise that the user's
 * firmware implements it.
 */
export const H168_PROBE_ENDPOINTS: readonly ProbeEndpoint[] = [
  {
    id: "device-basic-information",
    label: "Device basic information",
    path: "/api/device/basic_information",
    intervalMs: null,
    requiresAuth: false,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "monitoring-status",
    label: "Monitoring status",
    path: "/api/monitoring/status",
    intervalMs: 2_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "net-current-plmn",
    label: "Current PLMN",
    path: "/api/net/current-plmn",
    intervalMs: 10_000,
    requiresAuth: false,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "device-signal",
    label: "Signal",
    path: "/api/device/signal",
    intervalMs: 1_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "device-seccellinfo",
    label: "Secondary cells / CA",
    path: "/api/device/seccellinfo",
    intervalMs: 1_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "reference-shape",
  },
  {
    id: "device-nbrcellinfo",
    label: "Neighbor cells",
    path: "/api/device/nbrcellinfo",
    intervalMs: 3_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "reference-shape",
  },
  {
    id: "monitoring-traffic-statistics",
    label: "Traffic statistics",
    path: "/api/monitoring/traffic-statistics",
    intervalMs: 1_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "device-information",
    label: "Device information (diagnostic)",
    path: "/api/device/information",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "webserver-sestokinfo",
    label: "Session/token info",
    path: "/api/webserver/SesTokInfo",
    intervalMs: null,
    requiresAuth: false,
    defaultEnabled: true,
    evidence: "login-protocol",
  },
  {
    id: "user-state-login",
    label: "Login state",
    path: "/api/user/state-login",
    intervalMs: null,
    requiresAuth: false,
    defaultEnabled: true,
    evidence: "h168-reference-claimed",
  },
  {
    id: "developermode-developer-mode",
    label: "Developer mode (read-only candidate)",
    path: "/api/developermode/developer-mode",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "reference-shape",
  },
  {
    id: "developermode-developer-item",
    label: "Developer items (read-only candidate)",
    path: "/api/developermode/developer-item",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "reference-shape",
  },
  {
    id: "app-atport-status",
    label: "AT port status (GET only)",
    path: "/api/app/atport-status",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "reference-shape",
  },
  {
    id: "net-cell-info",
    label: "Generic cell info (candidate)",
    path: "/api/net/cell-info",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "candidate",
  },
  {
    id: "monitoring-month-statistics",
    label: "Monthly traffic statistics",
    path: "/api/monitoring/month_statistics",
    intervalMs: 60_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "wlan-host-list",
    label: "Connected WLAN clients",
    path: "/api/wlan/host-list",
    intervalMs: 10_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "monitoring-check-notifications",
    label: "Notifications / unread SMS count",
    path: "/api/monitoring/check-notifications",
    intervalMs: 10_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "sms-count",
    label: "SMS mailbox counts",
    path: "/api/sms/sms-count",
    intervalMs: 10_000,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "net-net-mode",
    label: "Network mode and LTE band mask",
    path: "/api/net/net-mode",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "net-net-mode-list",
    label: "Supported network modes and LTE bands",
    path: "/api/net/net-mode-list",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "net-lock-freq",
    label: "LTE / NR frequency lock state",
    path: "/api/net/lock-freq",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "network-band-frequency-list",
    label: "Supported LTE / NR frequency list",
    path: "/config/network/bandfreqlist.xml",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "dialup-mobile-dataswitch",
    label: "Mobile data switch",
    path: "/api/dialup/mobile-dataswitch",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "wlan-multi-basic-settings",
    label: "WLAN SSID index mapping",
    path: "/api/wlan/multi-basic-settings",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
  {
    id: "wlan-multi-macfilter-settings-ex",
    label: "WLAN client filter settings",
    path: "/api/wlan/multi-macfilter-settings-ex",
    intervalMs: null,
    requiresAuth: true,
    defaultEnabled: true,
    evidence: "h168-live-observed",
  },
];

export const H168_CORE_ENDPOINT_IDS = [
  "device-basic-information",
  "monitoring-status",
  "net-current-plmn",
  "device-signal",
  "device-seccellinfo",
  "device-nbrcellinfo",
  "monitoring-traffic-statistics",
  "monitoring-month-statistics",
  "wlan-host-list",
  "monitoring-check-notifications",
  "sms-count",
] as const;
